In [1]:
import pandas as pd

In [4]:
biomart_bed = pd.read_csv('beds/biomart.bed', sep='\t', header=None)
biomart_bed.columns = ['chrom', 'start', 'end', 'gene', 'strand', 'gc_content']
biomart_bed

      chrom      start        end    gene  strand  gc_content
0      chr1      64919      65920   OR4F5       1       32.06
1      chr1     451178     452179  OR4F29      -1       46.01
2      chr1     686154     687155  OR4F16      -1       46.01
3      chr1     923423     924424  SAMD11       1       66.59
4      chr1     958756     959757   NOC2L      -1       59.54
...     ...        ...        ...     ...     ...         ...
19371  chrX  155612086  155613087   SPRY3       1       37.19
19372  chrX  155612452  155613453   TMLHE      -1       37.16
19373  chrX  155880845  155881846   VAMP7       1       38.75
19374  chrX  155997196  155998197    IL9R       1       55.85
19375  chrX  156020461  156021462  WASH6P       1       59.75

[19376 rows x 6 columns]

In [5]:
biomart_bed['start'] = biomart_bed['start'] - 5000
biomart_bed['end'] = biomart_bed['end'] + 5000
biomart_bed

      chrom      start        end    gene  strand  gc_content
0      chr1      59919      70920   OR4F5       1       32.06
1      chr1     446178     457179  OR4F29      -1       46.01
2      chr1     681154     692155  OR4F16      -1       46.01
3      chr1     918423     929424  SAMD11       1       66.59
4      chr1     953756     964757   NOC2L      -1       59.54
...     ...        ...        ...     ...     ...         ...
19371  chrX  155607086  155618087   SPRY3       1       37.19
19372  chrX  155607452  155618453   TMLHE      -1       37.16
19373  chrX  155875845  155886846   VAMP7       1       38.75
19374  chrX  155992196  156003197    IL9R       1       55.85
19375  chrX  156015461  156026462  WASH6P       1       59.75

[19376 rows x 6 columns]

In [6]:
biomart_bed.to_csv('beds/biomart_10kb.bed', sep='\t', header=False, index=False)